name: sf-devops-script-deployment	

# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events
 push:
   branches:
    - main

   paths:
    - 'snowflake-queries/**' # location

 workflow_dispatch:

jobs:
  deploy-Snowflake-changes-job:
    runs-on: ubuntu-latest
      
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch 
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.11.x
        uses: actions/setup-python@v2.2.1

        with:
          python-version: 3.11.x

      - name: Run schemachange for DEV
        if: ${{ steps.extract_branch.outputs.branch == 'DEV' }}
        env:
          NAME: 'DEV'
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.DEV_SF_ROLE }}
          SF_DATABASE: ${{ secrets.DEV_SF_DATABASE }}
          SF_WAREHOUSE: ${{ secrets.DEV_SF_WAREHOUSE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          BRANCH_NAME_FOR_CONFIG: ${{ steps.extract_branch.outputs.branch }}

        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange==3.7.0

          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE_DEV.CHANGE_HISTORY    
